/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The web app polls this to decide between the assistant and the offline notice.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Abstention */
        Abstention: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "out_of_scope" | "insufficient_sources" | "medical_advice" | "unsafe";
            /** Suggestion */
            suggestion: string;
        };
        /** ApiMonograph */
        ApiMonograph: {
            /** Part */
            part: string;
            /** Volume */
            volume: string;
        };
        /** Biodiversity */
        Biodiversity: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /** Indianbioresource */
            indianBioResource: boolean;
            /** Normallytradedcommodity */
            normallyTradedCommodity: boolean | "unknown";
        };
        /** Citation */
        Citation: {
            /** Cited Text */
            cited_text: string;
            /** Doc Type */
            doc_type: string;
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "IN" | "INTL";
            /**
             * Locator
             * @description e.g. 's.3(p)', 'Rule 158B(1)(b)', 'Art. 27.3(b)'
             */
            locator: string;
            /** Source Id */
            source_id: string;
            /** Source Title */
            source_title: string;
            /** Url */
            url: string;
            /** Verified */
            verified: boolean;
            /** Version Label */
            version_label: string;
        };
        /** Confidence */
        Confidence: {
            /**
             * Band
             * @enum {string}
             */
            band: "high" | "medium" | "low";
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** Deposit */
        Deposit: {
            /** Budapest */
            budapest: boolean;
            /** Cite */
            cite: string;
            /**
             * Indianidas
             * @default []
             */
            indianIDAs: string[];
        };
        /** DrugSchedules */
        DrugSchedules: {
            /** Cite */
            cite: string;
            /**
             * Heavymetaltesting
             * @default null
             */
            heavyMetalTesting: boolean | null;
            /** Schedulee1 */
            scheduleE1: boolean | "unknown";
        };
        /** Escalation */
        Escalation: {
            /**
             * Available
             * @default true
             * @constant
             */
            available: true;
            /**
             * Ticket Id
             * @default null
             */
            ticket_id: string | null;
        };
        /** Export */
        Export: {
            /** Cite */
            cite: string;
            /** Restricted */
            restricted: boolean | "unknown";
        };
        /** GI */
        GI: {
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["GITag"][];
        };
        /** GITag */
        GITag: {
            /** Cite */
            cite: string;
            /** Name */
            name: string;
            /** Regno */
            regNo: string;
        };
        /** Health */
        Health: {
            /** Corpus Version */
            corpus_version: string;
            /** Embed Model */
            embed_model: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /**
         * JurisdictionAnswer
         * @description One pane. Answers for different jurisdictions are never merged.
         */
        JurisdictionAnswer: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            confidence: components["schemas"]["Confidence"];
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "IN" | "INTL";
            /** Markdown */
            markdown: string;
        };
        /** LandmarkPatent */
        LandmarkPatent: {
            /** Cite */
            cite: string;
            /** Number */
            number: string;
            /** Office */
            office: string;
            /** Outcome */
            outcome: string;
            /** Title */
            title: string;
            /** Year */
            year: number;
        };
        /**
         * MaterialIPProfile
         * @description `cite` fields hold a manifest source id, or 'unknown' when unverified.
         */
        MaterialIPProfile: {
            biodiversity: components["schemas"]["Biodiversity"];
            /** @default null */
            deposit: components["schemas"]["Deposit"] | null;
            drugSchedules: components["schemas"]["DrugSchedules"];
            export: components["schemas"]["Export"];
            gi: components["schemas"]["GI"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "plant" | "microbe" | "animal" | "mineral";
            /**
             * Lastverified
             * @description ISO date
             */
            lastVerified: string;
            monographs: components["schemas"]["Monographs"];
            patentability: components["schemas"]["Patentability"];
            patents: components["schemas"]["Patents"];
            tk: components["schemas"]["TraditionalKnowledge"];
            /** @default null */
            wildlife: components["schemas"]["Wildlife"] | null;
        };
        /** Monographs */
        Monographs: {
            /** @default null */
            api: components["schemas"]["ApiMonograph"] | null;
            /** Cite */
            cite: string;
        };
        /** PatentSearch */
        PatentSearch: {
            /** Googlepatents */
            googlePatents: string;
            /** Inpass */
            inpass: string;
            /** Patentscope */
            patentscope: string;
        };
        /** Patentability */
        Patentability: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /** Note */
            note: string;
        };
        /** Patents */
        Patents: {
            /**
             * Landmark
             * @default []
             */
            landmark: components["schemas"]["LandmarkPatent"][];
            search: components["schemas"]["PatentSearch"];
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Model */
            model: string;
            /**
             * Name
             * @enum {string}
             */
            name: "anthropic" | "groq";
        };
        /** RegistryPointer */
        RegistryPointer: {
            /** Action */
            action: string;
            cite: components["schemas"]["Citation"];
            /**
             * Fee Note
             * @default null
             */
            fee_note: string | null;
            /**
             * Form
             * @default null
             */
            form: string | null;
            /** Registry */
            registry: string;
            /** Url */
            url: string;
        };
        /** SahayakAnswer */
        SahayakAnswer: {
            /**
             * Abs
             * @default null
             */
            abs: {
                [key: string]: unknown;
            } | null;
            /** @default null */
            abstained: components["schemas"]["Abstention"] | null;
            /** Answers */
            answers: components["schemas"]["JurisdictionAnswer"][];
            /**
             * Classification
             * @default null
             */
            classification: {
                [key: string]: unknown;
            } | null;
            /**
             * Disclaimer
             * @default This is information, not legal advice. Verify with the cited source or a qualified IP facilitator before acting on it.
             */
            disclaimer: string;
            /**
             * @default {
             *       "available": true,
             *       "ticket_id": null
             *     }
             */
            escalation: components["schemas"]["Escalation"];
            /** Id */
            id: string;
            /**
             * Jurisdiction Mode
             * @enum {string}
             */
            jurisdiction_mode: "IN" | "INTL" | "BOTH";
            /**
             * Language
             * @description BCP-47, e.g. 'hi', 'mr', 'ta', 'en'
             */
            language: string;
            /**
             * Next Steps
             * @default []
             */
            next_steps: components["schemas"]["RegistryPointer"][];
            /**
             * Persona
             * @default null
             */
            persona: ("practitioner" | "researcher" | "startup" | "cultivator") | null;
            provider: components["schemas"]["ProviderInfo"];
            /** Question */
            question: string;
        };
        /** TraditionalKnowledge */
        TraditionalKnowledge: {
            /** Cite */
            cite: string;
            /**
             * Classicaltexts
             * @default []
             */
            classicalTexts: string[];
            /**
             * Tkdl
             * @enum {string}
             */
            tkdl: "documented" | "unknown";
        };
        /** Wildlife */
        Wildlife: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /**
             * Citeslisted
             * @default null
             */
            citesListed: boolean | "unknown" | null;
            /**
             * Protectedschedule
             * @default null
             */
            protectedSchedule: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
