/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/abs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abs Helper */
        post: operations["abs_helper_abs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Formulation
         * @description One question at a time: send the answers so far, get the next question or the result.
         */
        post: operations["classify_formulation_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consent */
        get: operations["get_consent_consent_get"];
        put?: never;
        /** Set Consent */
        post: operations["set_consent_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate */
        post: operations["escalate_escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The web app polls this to decide between the assistant and the offline notice.
         *     It never loads a model, so it answers instantly even on a cold start.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{kind}/{material_id}/ipr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Material Ipr */
        get: operations["material_ipr_materials__kind___material_id__ipr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registries */
        get: operations["list_registries_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbsResult */
        AbsResult: {
            /** Ip Approval Needed */
            ip_approval_needed: boolean;
            /**
             * Route
             * @enum {string}
             */
            route: "nba_approval" | "sbb_intimation" | "exempt_check" | "not_applicable";
            /** Steps */
            steps: components["schemas"]["Line"][];
            /** Summary */
            summary: string;
            /**
             * Verified On
             * @default 2026-09-17
             */
            verified_on: string;
        };
        /** AbsStep */
        AbsStep: {
            next_question?: components["schemas"]["Question"] | null;
            result?: components["schemas"]["AbsResult"] | null;
        };
        /** Abstention */
        Abstention: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "out_of_scope" | "insufficient_sources" | "medical_advice" | "unsafe";
            /** Suggestion */
            suggestion: string;
        };
        /** ApiMonograph */
        ApiMonograph: {
            /** Part */
            part: string;
            /** Volume */
            volume: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Context */
            context?: components["schemas"]["ContextItem"][];
            /**
             * Jurisdiction Mode
             * @default BOTH
             * @enum {string}
             */
            jurisdiction_mode: "IN" | "INTL" | "BOTH";
            /** Language */
            language?: string | null;
            /** Persona */
            persona?: ("practitioner" | "researcher" | "startup" | "cultivator") | null;
            /** Question */
            question: string;
        };
        /** Biodiversity */
        Biodiversity: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /** Indianbioresource */
            indianBioResource: boolean | "unknown";
            /** Normallytradedcommodity */
            normallyTradedCommodity: boolean | "unknown";
        };
        /** Citation */
        Citation: {
            /** Cited Text */
            cited_text: string;
            /** Doc Type */
            doc_type: string;
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "IN" | "INTL";
            /**
             * Locator
             * @description e.g. 's.3(p)', 'Rule 158B(1)(b)', 'Art. 27.3(b)'
             */
            locator: string;
            /** Source Id */
            source_id: string;
            /** Source Title */
            source_title: string;
            /** Url */
            url: string;
            /** Verified */
            verified: boolean;
            /** Version Label */
            version_label: string;
        };
        /** Cite */
        Cite: {
            /** Locator */
            locator: string;
            /** Source Id */
            source_id: string;
            /** Verified */
            verified: boolean;
        };
        /** ClassificationResult */
        ClassificationResult: {
            /**
             * Category
             * @enum {string}
             */
            category: "cosmetic" | "ayurveda_aahar" | "classical" | "patent_proprietary" | "phytopharmaceutical" | "new_drug";
            /** Decided By */
            decided_by: string;
            /**
             * Disclaimer
             * @default This classification is information, not legal advice. Lines marked 'verify' point at the right law but the exact provision has not been checked yet.
             */
            disclaimer: string;
            /** Ip Posture */
            ip_posture: components["schemas"]["Line"][];
            /** Label */
            label: string;
            /** Requires */
            requires: components["schemas"]["Line"][];
            /**
             * Verified On
             * @default 2026-09-17
             */
            verified_on: string;
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /**
             * Answers
             * @default {}
             */
            answers: {
                [key: string]: boolean;
            };
        };
        /** ClassifyStep */
        ClassifyStep: {
            /** Asked */
            asked: number;
            next_question?: components["schemas"]["Question"] | null;
            result?: components["schemas"]["ClassificationResult"] | null;
        };
        /** Confidence */
        Confidence: {
            /**
             * Band
             * @enum {string}
             */
            band: "high" | "medium" | "low";
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /** Granted */
            granted: boolean;
            /**
             * Scope
             * @enum {string}
             */
            scope: "assistant" | "transcript";
        };
        /** ConsentState */
        ConsentState: {
            /** Assistant */
            assistant: boolean;
            /** Transcript */
            transcript: boolean;
        };
        /** ContextItem */
        ContextItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
        };
        /** Deposit */
        Deposit: {
            /** Budapest */
            budapest: boolean;
            /** Cite */
            cite: string;
            /**
             * Indianidas
             * @default []
             */
            indianIDAs: string[];
        };
        /** DrugSchedules */
        DrugSchedules: {
            /** Cite */
            cite: string;
            /**
             * Heavymetaltesting
             * @default null
             */
            heavyMetalTesting: boolean | null;
            /** Schedulee1 */
            scheduleE1: boolean | "unknown";
        };
        /** EscalateRequest */
        EscalateRequest: {
            /** Answer Id */
            answer_id?: string | null;
            /** Contact */
            contact?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** EscalateResult */
        EscalateResult: {
            /** Facilitators */
            facilitators: components["schemas"]["FacilitatorOut"][];
            /** Note */
            note: string;
            /** Status */
            status: string;
            /** Ticket Id */
            ticket_id: string;
        };
        /** Escalation */
        Escalation: {
            /**
             * Available
             * @default true
             * @constant
             */
            available: true;
            /**
             * Ticket Id
             * @default null
             */
            ticket_id: string | null;
        };
        /** Export */
        Export: {
            /** Cite */
            cite: string;
            /** Restricted */
            restricted: boolean | "unknown";
        };
        /** FacilitatorOut */
        FacilitatorOut: {
            /** Body */
            body: string;
            /** Contact */
            contact: string;
            /** Name */
            name: string;
            /** Source Url */
            source_url: string;
        };
        /** GI */
        GI: {
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["GITag"][];
        };
        /** GITag */
        GITag: {
            /** Cite */
            cite: string;
            /** Name */
            name: string;
            /** Regno */
            regNo: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Corpus Version */
            corpus_version: string;
            /** Database */
            database: boolean;
            /** Embed Model */
            embed_model: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /**
         * JurisdictionAnswer
         * @description One pane. Answers for different jurisdictions are never merged.
         */
        JurisdictionAnswer: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            confidence: components["schemas"]["Confidence"];
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "IN" | "INTL";
            /** Markdown */
            markdown: string;
        };
        /** LandmarkPatent */
        LandmarkPatent: {
            /** Cite */
            cite: string;
            /** Number */
            number: string;
            /** Office */
            office: string;
            /** Outcome */
            outcome: string;
            /** Title */
            title: string;
            /** Year */
            year: number;
        };
        /** Line */
        Line: {
            cite: components["schemas"]["Cite"];
            /** Text */
            text: string;
        };
        /**
         * MaterialIPProfile
         * @description `cite` fields hold a manifest source id, or 'unknown' when unverified.
         */
        MaterialIPProfile: {
            biodiversity: components["schemas"]["Biodiversity"];
            /** @default null */
            deposit: components["schemas"]["Deposit"] | null;
            drugSchedules: components["schemas"]["DrugSchedules"];
            export: components["schemas"]["Export"];
            gi: components["schemas"]["GI"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "plant" | "microbe" | "animal" | "mineral";
            /**
             * Lastverified
             * @description ISO date; null = never verified
             * @default null
             */
            lastVerified: string | null;
            monographs: components["schemas"]["Monographs"];
            patentability: components["schemas"]["Patentability"];
            patents: components["schemas"]["Patents"];
            tk: components["schemas"]["TraditionalKnowledge"];
            /** @default null */
            wildlife: components["schemas"]["Wildlife"] | null;
        };
        /** Monographs */
        Monographs: {
            /** @default null */
            api: components["schemas"]["ApiMonograph"] | null;
            /** Cite */
            cite: string;
        };
        /** PatentSearch */
        PatentSearch: {
            /** Googlepatents */
            googlePatents: string;
            /** Inpass */
            inpass: string;
            /** Patentscope */
            patentscope: string;
        };
        /** Patentability */
        Patentability: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /** Note */
            note: string;
        };
        /** Patents */
        Patents: {
            /**
             * Landmark
             * @default []
             */
            landmark: components["schemas"]["LandmarkPatent"][];
            search: components["schemas"]["PatentSearch"];
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Model */
            model: string;
            /**
             * Name
             * @enum {string}
             */
            name: "anthropic" | "groq";
        };
        /** PurgeResult */
        PurgeResult: {
            /** Deleted */
            deleted: {
                [key: string]: number;
            };
        };
        /** Question */
        Question: {
            /**
             * Help
             * @default
             */
            help: string;
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** RegistryOut */
        RegistryOut: {
            /** Cite Locator */
            cite_locator: string | null;
            /** Cite Source Id */
            cite_source_id: string | null;
            /** Fee Note */
            fee_note: string | null;
            /** Forms */
            forms: unknown[];
            /** Id */
            id: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Name */
            name: string;
            /** Regime */
            regime: string[];
            /** Url */
            url: string;
        };
        /** RegistryPointer */
        RegistryPointer: {
            /** Action */
            action: string;
            cite: components["schemas"]["Citation"];
            /**
             * Fee Note
             * @default null
             */
            fee_note: string | null;
            /**
             * Form
             * @default null
             */
            form: string | null;
            /** Registry */
            registry: string;
            /** Url */
            url: string;
        };
        /** SahayakAnswer */
        SahayakAnswer: {
            /**
             * Abs
             * @default null
             */
            abs: {
                [key: string]: unknown;
            } | null;
            /** @default null */
            abstained: components["schemas"]["Abstention"] | null;
            /** Answers */
            answers: components["schemas"]["JurisdictionAnswer"][];
            /**
             * Classification
             * @default null
             */
            classification: {
                [key: string]: unknown;
            } | null;
            /**
             * Disclaimer
             * @default This is information, not legal advice. Verify with the cited source or a qualified IP facilitator before acting on it.
             */
            disclaimer: string;
            /**
             * @default {
             *       "available": true,
             *       "ticket_id": null
             *     }
             */
            escalation: components["schemas"]["Escalation"];
            /** Id */
            id: string;
            /**
             * Jurisdiction Mode
             * @enum {string}
             */
            jurisdiction_mode: "IN" | "INTL" | "BOTH";
            /**
             * Language
             * @description BCP-47, e.g. 'hi', 'mr', 'ta', 'en'
             */
            language: string;
            /**
             * Next Steps
             * @default []
             */
            next_steps: components["schemas"]["RegistryPointer"][];
            /**
             * Persona
             * @default null
             */
            persona: ("practitioner" | "researcher" | "startup" | "cultivator") | null;
            provider: components["schemas"]["ProviderInfo"];
            /** Question */
            question: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Doc Type */
            doc_type: string;
            /** Id */
            id: string;
            /** Issuer */
            issuer: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Regime */
            regime: string[];
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Versions */
            versions: components["schemas"]["SourceVersionOut"][];
        };
        /** SourceVersionOut */
        SourceVersionOut: {
            /** Chunks */
            chunks: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Sha256 */
            sha256: string;
            /** Superseded */
            superseded: boolean;
            /** Version Label */
            version_label: string;
        };
        /** SourcesOut */
        SourcesOut: {
            /** Changelog Markdown */
            changelog_markdown: string;
            /** Corpus Version */
            corpus_version: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /** TraditionalKnowledge */
        TraditionalKnowledge: {
            /** Cite */
            cite: string;
            /**
             * Classicaltexts
             * @default []
             */
            classicalTexts: string[];
            /**
             * Tkdl
             * @enum {string}
             */
            tkdl: "documented" | "unknown";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Wildlife */
        Wildlife: {
            /**
             * Cites
             * @default []
             */
            cites: string[];
            /**
             * Citeslisted
             * @default null
             */
            citesListed: boolean | "unknown" | null;
            /**
             * Protectedschedule
             * @default null
             */
            protectedSchedule: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    abs_helper_abs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsStep"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header: {
                /** @description anonymous id from the browser */
                "x-session-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description status, answer, done */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_formulation_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyStep"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consent_consent_get: {
        parameters: {
            query?: never;
            header: {
                /** @description anonymous id from the browser */
                "x-session-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_consent_consent_post: {
        parameters: {
            query?: never;
            header: {
                /** @description anonymous id from the browser */
                "x-session-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_escalate_post: {
        parameters: {
            query?: never;
            header: {
                /** @description anonymous id from the browser */
                "x-session-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    material_ipr_materials__kind___material_id__ipr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "plant" | "microbe" | "animal" | "mineral";
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialIPProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_me_delete: {
        parameters: {
            query?: never;
            header: {
                /** @description anonymous id from the browser */
                "x-session-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_registries_registry_get: {
        parameters: {
            query?: {
                regime?: string | null;
                jurisdiction?: ("IN" | "INTL") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesOut"];
                };
            };
        };
    };
}
